#!/bin/sh

# Copyright © 2011-2022 Jakub Wilk <jwilk@jwilk.net>
# SPDX-License-Identifier: MIT

if [ $# -ne 2 ]
then
    me=${0##*/}
    printf 'Usage: %s TAR-FILE-1 TAR-FILE-2\n' "$me" >&2
    exit 1
fi

set -e

tar1="$1"
tar2="$2"
tmpdir=$(mktemp -t -d tardiff.XXXXXX)
base1=${tar1##*/}
base2=${tar2##*/}
mkdir -p "$tmpdir/a/$base1/"
mkdir -p "$tmpdir/b/$base2/"
tar -xvvf "$tar1" -C "$tmpdir/a/$base1/" | LC_ALL=C sort -k6 > "$tmpdir/a/${base1}.list"
tar -xvvf "$tar2" -C "$tmpdir/b/$base2/" | LC_ALL=C sort -k6 > "$tmpdir/b/${base2}.list"
cd "$tmpdir"
if [ $(ls -Aq "a/$base1/" | wc -l) -eq 1 ] && [ $(ls -Aq "b/$base2/" | wc -l) -eq 1 ]
then
    mv "a/$base1/"* "a/$base1/*"
    mv "b/$base2/"* "b/$base2/*"
    sed -i -E -e 's,^(([^ ]+ +){5})([^/]*),\1*,' \
        "a/$base1.list" \
        "b/$base2.list"
fi
echo diff --wdiff "a/${base1}.list" "b/${base2}.list"
echo --- "a/${base1}.list"
echo +++ "b/${base2}.list"
wdiff "a/${base1}.list" "b/${base2}.list" | sed -e 's/^/ /'
diff -urN "a/${base1}/" "b/${base2}/" | cat
cd /
rm -rf "$tmpdir"

# vim:ts=4 sts=4 sw=4 et
