#!/bin/sh

# Copyright © 2011, 2012 Jakub Wilk <jwilk@jwilk.net>

# Redistribution and use in source and compiled forms, with or without
# modification, are permitted under any circumstances. No warranty.

if [ $# -ne 2 ]
then
    printf 'Usage: %s <tar1> <tar2>\n' "$0" >&2
    exit 1
fi

set -e

tar1="$1"
tar2="$2"
tmpdir=$(mktemp -t -d)
base1=$(basename "$tar1")
base2=$(basename "$tar2")
mkdir -p "$tmpdir/a/$base1/"
mkdir -p "$tmpdir/b/$base2/"
tar -xvvf "$tar1" -C "$tmpdir/a/$base1/" | LC_ALL=C sort -k6 > "$tmpdir/a/${base1}.list"
tar -xvvf "$tar2" -C "$tmpdir/b/$base2/" | LC_ALL=C sort -k6 > "$tmpdir/b/${base2}.list"
cd "$tmpdir"
if [ $(ls "a/$base1/" | wc -l) -eq 1 ] && [ $(ls "b/$base2/" | wc -l) -eq 1 ]
then
    mv "a/$base1/"* "a/$base1/*"
    mv "b/$base2/"* "b/$base2/*"
    sed -i -r -e 's,(([^ ]+ +){5})([^/]*),\1*,' \
        "a/$base1.list" \
        "b/$base2.list"
fi
echo diff --wdiff "a/${base1}.list" "b/${base2}.list"
echo --- "a/${base1}.list"
echo +++ "b/${base2}.list"
wdiff "a/${base1}.list" "b/${base2}.list" | sed -e 's/^/ /'
diff -urN "a/${base1}/" "b/${base2}/" | cat
cd /
rm -rf "$tmpdir"

# vim:ts=4 sts=4 sw=4 et
